/** People, for names of individuals: account holders, names on cards, senders and recipients. */
export const PEOPLE = [
  "Dale Cooper",
  "Laura Palmer",
  "Audrey Horne",
  "Harry Truman",
  "Lucy Moran",
  "Andy Brennan",
  "Tommy Hill",
  "Shelly Johnson",
  "Bobby Briggs",
  "Donna Hayward",
  "James Hurley",
  "Norma Jennings",
  "Ed Hurley",
  "Nadine Hurley",
  "Josie Packard",
  "Catherine Martell",
  "Pete Martell",
  "Ben Horne",
  "Leland Palmer",
  "Sarah Palmer",
  "Maddy Ferguson",
  "Leo Johnson",
  "Albert Rosenfield",
  "Gordon Cole",
  "Denise Bryson",
  "Margaret Lanterman",
  "Lawrence Jacoby",
  "Garland Briggs",
  "Annie Blackburn",
  "Harold Smith",
  "Jerry Horne",
  "Richard Tremayne",
  "Mike Nelson",
  "Hank Jennings",
  "Eileen Hayward",
  "Will Hayward",
  "Phillip Gerard",
  "Diane Evans",
  "Tammy Preston",
  "Janey-E Jones",
];

/** Places, for businesses: merchants, companies, counterparties. */
export const PLACES = [
  "Double R Diner",
  "Great Northern Hotel",
  "Packard Sawmill",
  "Horne's Department Store",
  "One Eyed Jacks",
  "The Roadhouse",
  "Big Ed's Gas Farm",
  "Blue Pine Lodge",
  "Ghostwood Estates",
  "Martell Lumber",
  "Twin Peaks Savings & Loan",
  "Lamplighter Inn",
  "Timber Room",
  "Glastonbury Grove Tours",
  "Owl Cave Outfitters",
  "Black Lodge Holdings",
  "White Lodge Ventures",
  "Sparkwood & 21 Supply",
  "Pearl Lakes Resort",
  "Calhoun Memorial Hospital",
  "Bookhouse Boys Club",
  "Rancho Rosa Estates",
  "Lucky 7 Insurance",
  "Silver Mustang Casino",
  "Fat Trout Trailer Park",
  "Dead Dog Farm",
  "Hap's Diner",
  "Invitation to Love Productions",
  "Eckhardt Industries",
  "Twin Peaks Gazette",
];

/** Lines for free text: notes, memos, descriptions. */
export const LINES = [
  "Damn fine cup of coffee",
  "The owls are not what they seem",
  "Cherry pie and coffee",
  "Diane, 11:30 a.m.",
  "Fire walk with me",
  "It is happening again",
  "The log will testify",
  "Let's rock",
  "That gum you like is coming back in style",
  "Every day, give yourself a present",
  "Wrapped in plastic",
  "Through the darkness of future past",
  "Meet me at the Roadhouse",
  "Sheriff's department supplies",
  "Donuts for the station",
];
